# Generated by Django 2.1.2 on 2018-12-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renewing',
            options={'verbose_name': '延長', 'verbose_name_plural': '延長'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='発行日'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='opac.Library', verbose_name='所蔵場所'),
        ),
    ]
